# Fan Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acacia360-app-chart.fullname" . }}-fan
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
    app: fan-service
spec:
  replicas: {{ .Values.fan.replicaCount }}
  selector:
    matchLabels:
      app: fan-service
  template:
    metadata:
      labels:
        app: fan-service
    spec:
      containers:
        - name: fan-service
          image: "{{ .Values.fan.image.repository }}:{{ .Values.fan.image.tag }}"
          imagePullPolicy: {{ .Values.fan.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.fan.service.port }}

          envFrom:
            - configMapRef:
                name: {{ include "acacia360-app-chart.fullname" . }}-fan-config
            - secretRef:
                name: {{ include "acacia360-app-chart.fullname" . }}-fan-secret

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "acacia360-app-chart.fullname" . }}-fan-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "acacia360-app-chart.fullname" . }}-fan-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "acacia360-app-chart.fullname" . }}-fan-secret
                  key: JWT_SECRET

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.fan.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.fan.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            {{- toYaml .Values.fan.resources | nindent 12 }}
