# Floor Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acacia360-app-chart.fullname" . }}-floor-config
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.floor.config.PORT }}"
  DB_HOST: "{{ .Values.floor.config.DB_HOST }}"
  DB_PORT: "{{ .Values.floor.config.DB_PORT }}"
  DB_NAME: "{{ .Values.floor.config.DB_NAME }}"

  # Internal microservice URLs
  USER_SERVICE_URL: "{{ .Values.gateway.config.USER_SERVICE_URL }}"
