# Gateway Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acacia360-app-chart.fullname" . }}-gateway
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
    app: gateway-service
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.gateway.service.port }}

          envFrom:
            - configMapRef:
                name: {{ include "acacia360-app-chart.fullname" . }}-gateway-config
            - secretRef:
                name: {{ include "acacia360-app-chart.fullname" . }}-gateway-secret

          # Health Checks
          livenessProbe:
            httpGet:
              path: /health # Assuming your service has a /health endpoint
              port: {{ .Values.gateway.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.gateway.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}