# Housekeeping Maintenance Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "acacia360-app-chart.fullname" .) "housekeeping-maintenance" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
    app: housekeeping-maintenance-service
spec:
  replicas: {{ .Values.housekeepingMaintenance.replicaCount }}
  selector:
    matchLabels:
      app: housekeeping-maintenance-service
  template:
    metadata:
      labels:
        app: housekeeping-maintenance-service
    spec:
      containers:
        - name: housekeeping-maintenance-service
          image: "{{ .Values.housekeepingMaintenance.image.repository }}:{{ .Values.housekeepingMaintenance.image.tag }}"
          imagePullPolicy: {{ .Values.housekeepingMaintenance.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.housekeepingMaintenance.service.port }}

          envFrom:
            - configMapRef:
                name: {{ include "acacia360-app-chart.fullname" . }}-housekeeping-maintenance-config
            - secretRef:
                name: {{ include "acacia360-app-chart.fullname" . }}-housekeeping-maintenance-secret

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "acacia360-app-chart.fullname" . }}-housekeeping-maintenance-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "acacia360-app-chart.fullname" . }}-housekeeping-maintenance-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "acacia360-app-chart.fullname" . }}-housekeeping-maintenance-secret
                  key: JWT_SECRET

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.housekeepingMaintenance.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.housekeepingMaintenance.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            {{- toYaml .Values.housekeepingMaintenance.resources | nindent 12 }}
