# Housekeeping Maintenance Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "acacia360-app-chart.fullname" .) "housekeeping-maintenance-config" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.housekeepingMaintenance.config.PORT }}"
  DB_HOST: "{{ .Values.housekeepingMaintenance.config.DB_HOST }}"
  DB_PORT: "{{ .Values.housekeepingMaintenance.config.DB_PORT }}"
  DB_NAME: "{{ .Values.housekeepingMaintenance.config.DB_NAME }}"

  # Internal microservice URLs
  USER_SERVICE_URL: "{{ .Values.gateway.config.USER_SERVICE_URL }}"
