# User Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acacia360-app-chart.fullname" . }}-user-config
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.user.config.PORT }}"
  DB_HOST: "{{ .Values.user.config.DB_HOST }}"
  DB_PORT: "{{ .Values.user.config.DB_PORT }}"
  DB_NAME: "{{ .Values.user.config.DB_NAME }}"
  
  # Internal microservice URLs
  AUTHENTICATION_SERVICE_URL: "{{ .Values.gateway.config.AUTHENTICATION_SERVICE_URL }}"